micronaut.application.name=fraudDetector
micronaut.server.port=9999
micronaut.server.netty.event-loop-group.default.num-threads=1
micronaut.server.netty.worker-group.num-threads=1
micronaut.netty.event-loops.default.num-threads=1
micronaut.io.watch.enabled=false
micronaut.server.thread-selection=AUTO
# Disabilitar virtual threads se estiver no Java 21 para economizar stack
micronaut.server.netty.use-native-transport=true
